name: quick_cart
description: "QuickCart - A mobile e-commerce app designed for fast, user-friendly shopping with streamlined cart and checkout features."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.0

  # Error Handling
  dartz: ^0.10.1
  equatable: ^2.0.5

  # Network
  http: ^1.2.0
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # JSON Serialization
  json_annotation: ^4.8.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
